[pytest]
minversion = 6.0
addopts = -ra
    -q
    --cov=src
    --flake8
    --cov-report=term-missing
    --cov-branch
testpaths = tests
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    integration: mark test as integration
filterwarnings =
    ignore::DeprecationWarning
flake8-ignore =
    *.py E251 E302 E303 E305 E501 W292 W391
